app:
    resource: '@AppBundle/Controller/'
    type: annotation
admin_index:
  path:     /admin
  defaults: { _controller: AppBundle:Admin:index }
admin_profile:
  path:     /admin/profile
  defaults: { _controller: AppBundle:Admin:profile }
admin_question:
  path:     /admin/question
  defaults: { _controller: AppBundle:Admin:question }
admin_questioncreate:
  path:     /admin/question/create
  defaults: { _controller: AppBundle:Admin:questioncreate }
admin_skill:
  path:     /admin/skills
  defaults: { _controller: AppBundle:Admin:skills }
admin_skillcreate:
  path:     /admin/skills/create
  defaults: { _controller: AppBundle:Admin:skillscreate }
admin_filtered:
  path:     /admin/users/filtered
  defaults: { _controller: AppBundle:Admin:filtered }
inscription:
  path:     /inscription
  defaults: { _controller: AppBundle:Default:Inscription }
CreateUser:
  path:     /CreateUser
  defaults: { _controller: AppBundle:Default:CreateUser }