<?php

namespace AppBundle\Repository;

/**
 * awnsersRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class awnsersRepository extends \Doctrine\ORM\EntityRepository
{
}
