<?php

namespace AppBundle\Repository;

/**
 * qcm_entriesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class qcm_entriesRepository extends \Doctrine\ORM\EntityRepository
{
}
