<?php

namespace AppBundle\Repository;

/**
 * questionskillRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class questionskillRepository extends \Doctrine\ORM\EntityRepository
{
}
