<?php

namespace AppBundle\Repository;

/**
 * skill_lvlRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class skill_lvlRepository extends \Doctrine\ORM\EntityRepository
{
}
